### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by jeemok** [mozilla-services/audit-filter#12]
Thank you for the great package! I was trying to install it and use it on my project but couldn't seemed to get it working. The script and error is posted below. Sorry if I missed out any steps, please let me know!

**Package.json**
```
  "scripts": {
    "lint:deps": "npm audit --json | audit-filter --nsp-config=.nsprc --audit=-"
   }
```

**Error**
```
to be executed: "npm audit --json | audit-filter --nsp-config=.nsprc --audit=-"
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\dev\stdin'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (C:\Users\mok\project\node_modules\audit-filter\cli.js:35:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
```

**Comment by g-k** [comment]
Hey @jeemok sorry for the delay getting back to you! Feel free to @ mention me.

I haven't tested it on Windows. `-` is an alias for unix stdin and I'm not sure that exists on Windows.

If you don't mind writing the audit output to a file you could try something like:

```console
npm audit --json > npm-audit-output.json
audit-filter --nsp-config=.nsprc --audit=npm-audit-output.json
```

Let me know if that works for you.

**Comment by g-k** [comment]
This is also a bug.

node.js's `process.stdin` and Rust's `io::stdin()` https://doc.rust-lang.org/std/io/struct.Stdin.html should be platform aware, but since we're compiling to WASM it ends up using the linux path.

We can fix this with a runtime check either in node or rust.

Compiling separate WASM modules for each platform would work too, but defeats the purpose of using WASM.

**Comment by g-k** [comment]
We'll also need Windows CI to test this regression (possibly with appveyor).

**Comment by g-k** [comment]
This is actually hardcoded at https://github.com/mozilla-services/audit-filter/blob/6ad33458705a45f2fcbb1d645ad88d4e6ca7814b/pkg/cli.js#L30 so that should be easy to fix.

**Comment by rakeshramakrishnan** [comment]
Any workaround until the bug is patched?

**Comment by g-k** [comment]
@rakeshramakrishnan yep write to a tempfile as described in https://github.com/mozilla-services/audit-filter/issues/12#issuecomment-461882524

**Comment by g-k** [comment]
The challenge is passing https://nodejs.org/api/process.html#process_process_stdin as https://doc.rust-lang.org/std/io/struct.Stdin.html (or a reference to it) across the wasm boundary and `/dev/stdin` was a *nix only hack around that.

We'd probably want to check whether `wasm-bindgen` can do that and otherwise write a binding like this one for console log https://github.com/rustwasm/wasm-bindgen/blob/master/examples/console_log/src/lib.rs

Alternatively, we could write a shim to save to a tempfile on windows, but that seems pretty gross.
